### ISSUE TITLE
UICollectionView freezing

### ISSUE THREAD

**Issue by grant-park** [leoru/SwiftLoader#5] opened 2015-08-09 11:34 UTC
I think that some cover view or subview isn't being completely dismissed or removed because I can't access or interact with anything on my view after SwiftLoad.hide(). Sometimes, I'm able to access the view if I'm quick enough... http://stackoverflow.com/questions/31903892/removing-hidden-view-subview-to-unfreeze-main-view

**Comment by 10printhello** [comment] 2015-08-12 09:27
I had this problem when I was calling SwiftLoader.hide() when the SwiftLoader was already hidden.

**Comment by dfsklar** [comment] 2015-09-08 20:42
I am finding that this is a bug that occurs frequently when sending animated: true to the show invocation.  I cannot reproduce the problem if I send animated:false to the show() invocation.

A look at the code shows that yes it's very likely the problem is a cover view that refuses to go away.  So I am adding a "+1" to the complaint from @sungjp 

Note: I disagree with @10printhello that superfluous hide() invocations are required.

**Comment by 10printhello** [comment] 2015-09-09 09:15
@dfsklar Think you misunderstood my comment above. If Swiftloader isn't present and you call .Hide() then it causes the UI to freeze. I can replicate this issue every time.

**Comment by leoru** [comment] 2015-10-09 20:16
Fixed in v0.2.5

**Closed as completed by leoru** 2015-10-09 20:16 UTC
